### ISSUE TITLE
Tweak LLVM backend to work with GPU/GPU

### ISSUE THREAD

**Issue by rrnewton** [vollmerm/shallow-fission#5]

**Comment by tmcdonell** [comment]
Actually, is this still a priority given that we want to move scheduling into the shallow layer?

We should be able to just tell it that there are two GPU backends, one for each device. There could be some advantages of having the two separate backends know a little about each other (direct device-to-device transfers) even if they aren't cooperating by themselves to complete the same kernel, but I don't think that that helps the story we want to tell.

Having GPU/GPU would be necessary for a "fair" comparison of shallow-fission vs. iteration stealing, but maybe we can ignore that for now...

**Comment by rrnewton** [comment]
Wait, but if our idea is to _compare_ two approaches (shallow vs late), I thought the idea was that the late-fissioning, iteration farming version needed to support (one of) the same modes that the early-fissioning version does.

However, it does seem that if early-fissioning supports CPU/GPU via multiple, separate backends, then we can compare on that basis and it is not necessary to finish this ticket.
